// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/back.tsx";
import * as $3 from "./routes/countdown.tsx";
import * as $4 from "./routes/greet/[name].tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/page/[name].tsx";
import * as $$0 from "./islands/Back.tsx";
import * as $$1 from "./islands/Countdown.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/Footer.tsx";
import * as $$4 from "./islands/NavItem.tsx";
import * as $$5 from "./islands/NavTitle.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/back.tsx": $2,
    "./routes/countdown.tsx": $3,
    "./routes/greet/[name].tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/page/[name].tsx": $6,
  },
  islands: {
    "./islands/Back.tsx": $$0,
    "./islands/Countdown.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/Footer.tsx": $$3,
    "./islands/NavItem.tsx": $$4,
    "./islands/NavTitle.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
